# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'complete/pom.xml'
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'unaeem-subscription (e09e8db9-bd86-48ae-8eeb-eda17abcc24a)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/e09e8db9-bd86-48ae-8eeb-eda17abcc24a/resourceGroups/spring/providers/Microsoft.AppPlatform/Spring/my-spring'
    AppName: 'app1'
    UseStagingDeployment: false
    Package: 'complete/target/spring-boot-complete-0.0.1-SNAPSHOT.jar'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
